#%RAML 0.8
---
title: BPI - Load Balancer Service
baseUri: https://bpi.automation.api.rackspacecloud.com/2.0/{tenant_id}/loadbalancers
version: v2.0

documentation:
  - title: Business Process Interface - Load Balancer Service
    content: |
      # Business Process Interface
      ## Load Balancer Service
      **Markdown documentation here**

securitySchemes:
  - internalIdentity:
      description: Rackspace Internal Identity authentication
      type: x-auth-token
      describedBy:
        headers:
          X-Auth-Token:
            description: Used to send a valid Identity access token.
            type: string
        responses:
          401:
            description: |
              Bad or expired token. To fix, you should re-
              authenticate the user.
          403:
            description: |
              Bad request
      settings:
        identityServiceUri: https://identity-internal.api.rackspacecloud.com/v2.0/

securedBy: [internalIdentity]

/{device_id}:
    displayName: Loadbalancer  API Calls
    get:
        description: Returns a complete info about loadbalancer
        responses:
            200:
                body:
                    application/json:
                        example: !include devices.sample
                            
            404:
                body:
                    application/json:
                        example: !include error.sample
                                                                
    /configuration:
        displayName: Display the node configuration key.
        get:
            description: Config info for a given node.
            responses:
                200:
                    body:
                        application/json:
                            example: |
                                {
                                  "load_balancer_data": {
                                    "b64": "key"
                                  }
                                }

    /ha:
        displayName: Information about High Availability configuration.
        get:
            description: High Availability template.
            responses:
                200:
                    body:
                        application/json:
                            example: |
                                {
                                  "message": "This is a test template for High Availability"
                                }


    /vips:
        displayName: VIPs configured to devices
        get:
            description: VIPs in a device for the given device id
            responses:
                200:
                    body:
                        application/json:
                            example: !include vips.sample 
                404:
                    body:
                        application/json:
                            example: !include error.sample
                                
        post:
            description: Create a new VIP.
            body:
                application/json:
                    example: !include create_vip.sample

            responses:
                202:
                    body:
                        application/json:
                            example: !include event.sample
                                

        /{vip_id}:
            displayName: VIP Information for given VIP id.
            get:
                description: Information about single VIP.
                responses:
                    200:
                        body:
                            application/json:
                                example: !include vip.sample 
                    404:
                        body:
                            application/json:
                                example: !include error.sample
            put:
                description: Update VIP information.
                body:
                    application/json:
                        example: !include create_vip.sample
                              
                responses:
                    202:
                        body:
                            application/json:
                                example: !include event.sample
                                    
            delete:
                description: Delete VIP.
                body:
                    application/json:
                        example: |
                            {
                              "account_number": req"<Account Number>",
                              "comment": req"comment"
                            }
                responses:
                    202:
                        body:
                            application/json:
                                example: !include event.sample
                                    
            
            /nodes:
                displayName: Display nodes configured to a given vip id.
                get:
                    description: List nodes for single VIP.
                    responses:
                        200:
                            body:
                                application/json:
                                    example: !include nodes.sample

                /{node_id}:
                    displayName: Bind/Unbind given node_id with vip.
                    post:
                        description: Bind given node_id with VIP.
                        body:
                            application/json:
                                example: |
                                    {
                                      "account_number": req"<Account Number>"
                                    }
                        responses:
                            202:
                                body:
                                    application/json:
                                        example: !include event.sample

            
                    delete:
                        description: Unbind given node_id from VIP.
                        body:
                            application/json:
                                example: |
                                    {
                                      "account_number": req"<Account Number>"
                                    }
                        responses:
                            202:
                                body:
                                    application/json:
                                        example: !include event.sample
            
            /configuration:
                displayName: Activate/Deactivate VIP.
                post:
                    description: Activate the VIP.
                    body:
                        application/json:
                            example: |
                                {
                                  "account_number": req"<Account Number>"
                                }
                    responses:
                        202:
                            body:
                                application/json:
                                    example: !include event.sample
            
                delete:
                    description: Deactivate the VIP.
                    body:
                        application/json:
                            example: |
                                {
                                  "account_number": req"<Account Number>"
                                }
                    responses:
                        202:
                            body:
                                application/json:
                                    example: !include event.sample
      
            /stats:
                displayName: Display stats for given vip id.
                get:
                    description: Statistics for single VIP.
                    responses:
                        200:
                            body:
                                application/json:
                                    example: !include stats.sample
                        404:
                            body:
                                application/json:
                                    example: !include error.sample
            
    /nodes:
        displayName: Information about Nodes.
        get:
            description: Nodes in a device for the given device id
            responses:
                200:
                    body:
                        application/json:
                            example: !include node_device.sample
                404:
                    body:
                        application/json:
                            example: !include error.sample
        post:
            description: Create a new node.
            body:
                application/json:
                    example: !include create_node.sample
            responses:
                202:
                    body:
                        application/json:
                            example: !include event.sample

        /{node_id}:
            displayName: Information about a particular node.
            get:
                description: Node Information
                responses:
                    200:
                        body:
                            application/json:
                                example: !include node_info.sample
                    404:
                        body:
                            application/json:
                                example: !include error.sample
            put:
                description: Update node configuration.
                body:
                    application/json:
                        example: !include update_node.sample
                            
                responses:
                    202:
                        body:
                            application/json:
                                example: !include event.sample
            delete:
                description: Delete the Node.
                body:
                    application/json:
                        example: |
                            {
                              "account_number": req"<Account Number>"
                            }
                responses:
                    202:
                        body:
                            application/json:
                                example: !include event.sample
            /configuration:
                displayName: Activate/Deactivate node.
                post:
                    description: Activate the node.
                    body:
                        application/json:
                            example: |
                                {
                                  "account_number": req"<Account Number>"
                                }
                    responses:
                        202:
                            body:
                                application/json:
                                    example: !include event.sample
                delete:
                    description: Deactivate the node.
                    body:
                        application/json:
                            example: |
                                {
                                  "account_number": req"<Account Number>"
                                }
                    responses:
                        202:
                            body:
                                application/json:
                                    example: !include event.sample

            /stats:
                displayName: Statistics for node.
                get:
                    description: Display the stats for given node_id
                    responses:
                        200:
                            body:
                                application/json:
                                    example: !include node_stat.sample
                        404:
                            body:
                                application/json:
                                    example: !include error.sample
    /events:
        displayName: In flight requests (events) for asyncronous calls to create or modify load balancer resources.
        get:
            description: Returns a list of events.
            responses:
                200:
                    body:
                        application/json:
                            example: !include events.sample
                            
        /{event_id}:
            displayName: Details for a specific event.

            get:
                description: Returns a specfic event info.
                responses:
                    200:
                        body:
                            application/json:
                                example: !include event.sample
