#%RAML 0.8
---
title: BPI - Load Balancer Service
version: v2.0 <br> <p style="font-size:17px; color:black"><em>Last modified date - Oct 28, 2016 </em></p><hr>
baseUri: https://bpi.automation.api.rackspacecloud.com/2.0/{tenant_id}/loadbalancers
documentation:
- title: API Overview
  content: |
    This API exposes methods to view and manage Load Balancer resources

- title: Authentication and Authorization
  content: |
    Access to this API is granted through a valid token acquired through the Internal Identity service <pending link>.
    The token is passed within the *X-Auth-Token* HTTP header.

    ** Roles required to access API : <br>**
    "bpi_lbs_read" is required for GET calls <br>
    "bpi_lbs_write" is required for PUT, POST, DELETE calls <br>
- title: Standard errors
  content: |
    - **400**: Bad request.
    - **401**: Authentication error, the user does not have valid authentication details.
    - **403**: Forbidden, you are not authorized to view this resource.
    - **404**: The page or resource requested does not exist.
    - **500**: An indeterminate error occurred. This is caused by an unexpected error.
    - **501**: Retrieving a list of details is not supported and/or not implemented.
    - **510**: An indeterminate error occurred. This is caused by an unexpected error.

baseUriParameters:
  tenant_id:
    displayName: Tenant ID
    description: |
        The account number associated with the core_id
    type: integer

mediaType: application/json

securitySchemes:
  - internalIdentity:
      description: |
        Rackspace Internal Identity authentication
      type: x-auth-token
      describedBy:
        headers:
          X-Auth-Token:
            description: |
                Used to send a valid Identity access token.
            type: string
        responses:
          401:
            description: |
              Bad or expired token. To fix, you should re-authenticate the user.
          403:
            description: |
              User Doesn't have the required role.
      settings:
        identityServiceUri: https://identity-internal.api.rackspacecloud.com/v2.0/

securedBy: [internalIdentity]

/{device_id}:
    displayName: Device Resource
    description: |
        Using the device resource will allow you to retrieve information for the given device. 
        
        The resource also allows you to create, update, retrieve and delete on several of the
        device's sub-resources for the device you selected. You will be able to make these actions
        on the following sub-resources - configuration, ha, vips, nodes, and events.
    get:
        description: Retrieve device information
        responses:
            200:
                description: Successfully processed the request.
                body:
                    application/json:
                        example: !include devices.sample

            404:
                description: Not found.
                body:
                    application/json:
                        example: !include error.sample

    /configuration:
        displayName: Device configuration
        description: |
            Retrieves the load balancer configuration information for the specified
            device ID.
        get:
            description: Retrieve load balancer configuration details
            responses:
                200:
                    description: Successfully processed the request.
                    body:
                        application/json:
                            example: |
                                {
                                  "load_balancer_data": {
                                    "b64": "key"
                                  }
                                }

    /ha:
        displayName: High Availability configuration template
        description: |
            Retrieves the high availability configuration for
            the specified device ID.
        get:
            description: Show high availability configuration
            responses:
                200:
                    description: Successfully processed the request.
                    body:
                        application/json:
                            example: |
                                {
                                  "message": "This is a test template for High Availability"
                                }


    /vips:
        displayName: Manage Virtual IPs
        description: |
            Load balancers must have at least one virtual IP address that clients
            can use to balance traffic across nodes. You can use the manage virtual IPs
            operations to configure and manage the virtual IP addresses for the load
            balancer using the specified device ID.

            An IP can be passed into the `add Virtual IP` call as part of the request body,
            only if the IP exists within an existing Virtual.

            *When adding a Virtual IP, these fields are required: account_number, label, protocol,
            port, algorithm, persistence, admin_state, comment*
        get:
            description: Retrieve virtual IPs configuration
            responses:
                200:
                    description: Successfully processed the request.
                    body:
                        application/json:
                            example: !include vips.sample
                404:
                    description: Not found.
                    body:
                        application/json:
                            example: !include error.sample

        post:
            description: Add a Virtual IP
            body:
                application/json:
                    example: !include create_vip.sample

            responses:
                202:
                    description: The request has been accepted for processing.
                    body:
                        application/json:
                            example: !include event.sample


        /{vip_id}:
            displayName: Virtual IP
            description: |
                Use the virtual IPs information operations to retrieve and update
                information for a virtual IP configured for the specified device ID.

                Use the delete operation to remove a virtual IP from the device
                configuration.

                If you don't know the ID for a specified virtual IP, use the retrieve
                virtual IPs operation to find it.

                *When deleting, these fields are required: account_number, comment*
            get:
                description: Retrieve Virtual IP information
                responses:
                    200:
                        description: Successfully processed the request.
                        body:
                            application/json:
                                example: !include vip.sample
                    404:
                        description: Not found.
                        body:
                            application/json:
                                example: !include error.sample
            put:
                description: Update Virtual IP information
                body:
                    application/json:
                        example: !include create_vip.sample

                responses:
                    202:
                        description: The request has been accepted for processing.
                        body:
                            application/json:
                                example: !include event.sample

            delete:
                description: Delete a Virtual IP
                body:
                    application/json:
                        example: |
                            {
                              "account_number": "<Account Number> (required)",
                              "comment": "<comment> (required)"
                            }
                responses:
                    202:
                        description: The request has been accepted for processing.
                        body:
                            application/json:
                                example: !include event.sample

            /nodes:
                displayName: Virtual IP node configuration
                description: |
                    Retrieve information about the nodes associated with the
                    specified Virtual IP.
                get:
                    description: List nodes for the specified Virtual IP.
                    responses:
                        200:
                            description: Successfully processed the request.
                            body:
                                application/json:
                                    example: !include nodes.sample

                /{node_id}:
                    displayName: Manage Virtual IP node configuration
                    description: |
                        Use the Virtual IP node configuration operations to add or
                        remove a specified node from the Virtual IP configuration.

                        *When assigning a node to a virtual, this field is required: account_number*
                    post:
                        description: Assign node to Virtual IP
                        body:
                            application/json:
                                example: |
                                    {
                                      "account_number": "<Account Number>"
                                    }
                        responses:
                            202:
                                description: The request has been accepted for processing.
                                body:
                                    application/json:
                                        example: !include event.sample


                    delete:
                        description: Remove node from Virtual IP configuration
                        responses:
                            202:
                                description: The request has been accepted for processing.
                                body:
                                    application/json:
                                        example: !include event.sample

            /configuration:
                displayName: Manage Virtual IP status
                description: |
                   Use the Virtual IP configuration operations to enable or
                   disable a Virtual IP configured for a specified device.
                post:
                    description: Activate the Virtual IP.
                    body:
                        application/json:
                            example: |
                                {
                                  "account_number": "<Account Number> (required)"
                                }
                    responses:
                        202:
                            body:
                                application/json:
                                    example: !include event.sample

                delete:
                    description: Deactivate the Virtual IP.
                    body:
                        application/json:
                            example: |
                                {
                                  "account_number": "<Account Number> (required)"
                                }
                    responses:
                        202:
                            description: The request has been accepted for processing.
                            body:
                                application/json:
                                    example: !include event.sample

            /stats:
                displayName: Virtual IP statistics
                description: Retrieves usage data for the specified Virtual IP.
                get:
                    description: Show Virtual IP statistics
                    responses:
                        200:
                            description: Successfully processed the request.
                            body:
                                application/json:
                                    example: !include stats.sample
                        404:
                            description: Not found.
                            body:
                                application/json:
                                    example: !include error.sample

    /nodes:
        displayName: Nodes
        description: |
            A Node is a back-end device providing a service on a specified IP and port.

            Use the nodes operations to get information about the nodes configured for
            a specified device and to add a node.

            After a node has been defined, use the Virtual IP nodes configuration
            operations to assign the node to one or more Virtual IPs.

            *When adding a node to a device, these fields are rquired: account_number, label,
            ip, port, admin_state, health_strategy, vendor_extensions, comment*
        get:
            description: Nodes in a device for the given device id
            responses:
                200:
                    description: Successfully processed the request.
                    body:
                        application/json:
                            example: !include node_device.sample
                404:
                    body:
                        application/json:
                            example: !include error.sample
        post:
            description: Add a Node to a device
            body:
                application/json:
                    example: !include create_node.sample
            responses:
                202:
                    description: The request has been accepted for processing.
                    body:
                        application/json:
                            example: !include event.sample

        /{node_id}:
            displayName: Manage Node information
            description: |
                Use the node operations to view, update, or remove a
                specified node.
            get:
                description: Retrieve Node information
                responses:
                    200:
                        description: Successfully processed the request.
                        body:
                            application/json:
                                example: !include node_info.sample
                    404:
                        description: Not found.
                        body:
                            application/json:
                                example: !include error.sample
            put:
                description: Update node information
                body:
                    application/json:
                        example: !include update_node.sample

                responses:
                    202:
                        description: The request has been accepted for processing.
                        body:
                            application/json:
                                example: !include event.sample
            delete:
                description: Delete the Node.
                body:
                    application/json:
                        example: |
                            {
                              "account_number": "<Account Number> (required)"
                            }
                responses:
                    202:
                        description: The request has been accepted for processing.
                        body:
                            application/json:
                                example: !include event.sample
            /configuration:
                displayName: Manage Node status
                description: |
                    Use the node status operations to enable or disable a specified
                    Node included in the device configuration.

                    If you want to delete the node from the configuration file, use the
                    delete node operation.

                post:
                    description: Activate the Node.
                    body:
                        application/json:
                            example: |
                                {
                                  "account_number": "<Account Number> (required)"
                                }
                    responses:
                        202:
                            description: The request has been accepted for processing.
                            body:
                                application/json:
                                    example: !include event.sample
                delete:
                    description: Deactivate the Node.
                    body:
                        application/json:
                            example: |
                                {
                                  "account_number": "<Account Number> (required)"
                                }
                    responses:
                        202:
                            description: The request has been accepted for processing.
                            body:
                                application/json:
                                    example: !include event.sample

            /stats:
                displayName: Node statistics
                description: Retrieves usage data for a specified Node ID.
                get:
                    description: Show Node statistics
                    responses:
                        200:
                            description: Successfully processed the request.
                            body:
                                application/json:
                                    example: !include node_stat.sample
                        404:
                            description: Not found.
                            body:
                                application/json:
                                    example: !include error.sample
    /events:
        displayName: Events
        description: |
            Use the events operations to get information about requests to create or
            modify load balancer resources.

        get:
            description: List Events
            responses:
                200:
                    description: Successfully processed the request.
                    body:
                        application/json:
                            example: !include events.sample

        /{event_id}:
            displayName: Event ID details
            description: |
                Use the event ID details operation to get information about
                about a specific event including event type, status, message, and
                timestamp.

            get:
                description: Retrieves Event information using the specified event ID.
                responses:
                    200:
                        description: Successfully processed the request.
                        body:
                            application/json:
                                example: !include event.sample
